# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G8zqbHknxXvCHthuNfTSgHVeuusfE_-s
"""

import numpy as np
import pandas as pd
import matplotlib as plt

dataset=pd.read_csv("heart_failure_clinical_records_dataset.csv")
x=dataset.iloc[:,:-2].values
y=dataset.iloc[:,-1].values

x.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
model=scaler.fit(x_train)
x_train=model.transform(x_train)
x_test=model.transform(x_test)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.predict([[0,582,0,20,1,26500,1.9,130,1,0,4]])

y_pred=lr.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix
print(cm(y_test,y_pred))
accuracy_score(y_test,y_pred)

